### ISSUE TITLE
Add translations introduced by react-admin v4.4.0

### ISSUE THREAD

**Issue by szaffarano** [BlackBoxVision/react-admin-extensions#12]
Version 4.4.0 added the `Customize` component, which includes some new i18n keys.  More info [here](https://github.com/marmelab/react-admin/pull/8145/files#diff-9c049081c840402bbce64954f5985fd1e19dc731fdc5fac7b18eec8f13faebe5).

**Comment by JonatanSalas** [comment]
We've fixed this issue with the PR https://github.com/BlackBoxVision/react-admin-extensions/pull/10. We're going soon to release a new version of this package!

**Comment by JonatanSalas** [comment]
We've published version 4.4.0, you can upgrade:

```bash
npm i @blackbox-vision/ra-language-spanish@4.4.0
```

Let me know if this helps you!

**Comment by szaffarano** [comment]
Great! thanks a lot Jonatan
