### ISSUE TITLE
Cannot find module: '@blackbox-vision/ra-language-spanish'. Make sure this package is installed.

### ISSUE THREAD

**Issue by sebastianperruolo** [BlackBoxVision/react-admin-extensions#3]
Hi,

Thanks for sharing Spanish translations for react-admin!

I've updated from 3.12 to 3.16 and found this issue. I've tried installing this library on a new React Admin project but didn't work.
```
yarn create react-app test-admin
cd test-admin/
yarn add react-admin ra-data-json-server prop-types
yarn build
```
That works until I installed this library:

### yarn add @blackbox-vision/ra-language-spanish
```
yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "connected-react-router@^6.5.2".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "final-form@^4.20.2".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "react-final-form@^6.5.2".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "react-redux@^7.1.0".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "react-router@^5.1.0".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "react-router-dom@^5.1.0".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "redux@^3.7.2 || ^4.0.3".
warning "ra-data-json-server > ra-core@3.16.3" has unmet peer dependency "redux-saga@^1.0.0".
warning "react-admin > connected-react-router@6.9.1" has unmet peer dependency "history@^4.7.2".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.20.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @blackbox-vision/ra-language-spanish@3.16.1" has unmet peer dependency "ra-core@^3.14.0".
warning " > @blackbox-vision/ra-language-spanish@3.16.1" has incorrect peer dependency "react@^16.11.0".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @blackbox-vision/ra-language-spanish@3.16.1
info All dependencies
└─ @blackbox-vision/ra-language-spanish@3.16.1
Done in 6.34s.
```

### yarn build
```
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/App.js
Cannot find module: '@blackbox-vision/ra-language-spanish'. Make sure this package is installed.

You can install this package by running: yarn add @blackbox-vision/ra-language-spanish.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Is there something I wrong I'm doing or maybe installing wrong library version?

**Comment by manutuero** [comment]
Hi @sebastianperruolo, thanks for use our lib.

I've followed your instructions creating a new react app using yarn and installing the package `@blackbox-vision/ra-language-spanish` with version `"@blackbox-vision/ra-language-spanish": "^3.16.1"` and no error appearing.

<img width="1440" alt="Captura de Pantalla 2021-07-01 a la(s) 18 31 59" src="https://user-images.githubusercontent.com/11902162/124191810-b61b6700-da9a-11eb-80ae-45ec87103ee4.png">

<img width="1244" alt="Captura de Pantalla 2021-07-01 a la(s) 18 33 22" src="https://user-images.githubusercontent.com/11902162/124191885-d4816280-da9a-11eb-8c0d-e1608162eb56.png">

What node version you are using?

**Comment by joshf** [comment]
this is happening for me both locally and deploying to vercel

**Comment by JonatanSalas** [comment]
Would you mind to make a repro case repository? Also, which version of node/npm/yarn are you using?

**Comment by sebastianperruolo** [comment]
@manutuero thanks for the quick response!

In the screenshot you attached I can't see if you added the import as following:

```
import spanishMessages from "@blackbox-vision/ra-language-spanish";
```

My node, npm and yarn versions are:
```
$ node --version
v14.17.1
$ npm --version
6.14.13
$ yarn --version
1.22.10

```

**Comment by joshf** [comment]
-import spanishMessages from "@blackbox-vision/ra-language-spanish";
+import spanishMessages from "@blackbox-vision/ra-language-spanish/pkg";


this works

**Comment by sebastianperruolo** [comment]
Thanks @joshf that worked. That's not how it's mentioned on the README, right?.

**Comment by joshf** [comment]
It's not I am assuming it's a bug introduced when the repo moved

**Comment by manutuero** [comment]
@sebastianperruolo @joshf In fact, the import in the latest version was wrong. We will release a new version to fix this problem. Thanks for reporting us!

**Comment by manutuero** [comment]
@sebastianperruolo @joshf please try running:

```
yarn add @blackbox-vision/ra-language-spanish@3.16.2
```

**Comment by joshf** [comment]
@manutuero yes it fixes the problem
