### ISSUE TITLE
Jest tests: Cannot find module '@blackbox-vision/ra-language-spanish'

### ISSUE THREAD

**Issue by d1alogo** [BlackBoxVision/react-admin-extensions#4]
It works perfect from the App build (create react app), but it cannot find the module when running jest tests.
I think it has something to do with 
Jest looking for a file called index.js in the module root folder.
If i create and empty index.js file in the root folder Jest pass sucessfully.

This is the node_modules subfolder for the installed module:
└── ra-language-spanish
    ├── dist-src
    │   └── index.js
    ├── dist-types
    │   └── index.d.ts
    ├── dist-web
    │   ├── index.js
    │   └── index.js.map
    ├── package.json
    └── README.md

This is the Jest run failing ouput:

 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module '@blackbox-vision/ra-language-spanish' from 'src/providers/i18nProvider.js'

    Require stack:
      src/providers/i18nProvider.js
      src/App.js
      src/App.test.js

      2 | import polyglotI18nProvider from 'ra-i18n-polyglot'
      3 | import englishMessages from 'ra-language-english'
    > 4 | import spanishMessages from '@blackbox-vision/ra-language-spanish'
        | ^
      5 | import frenchMessages from 'ra-language-french'
      6 | import italianMessages from 'ra-language-italian'
      7 | import merge from 'lodash/merge'

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/providers/i18nProvider.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        7.515 s, estimated 10 s
Ran all test suites.

**Comment by JonatanSalas** [comment]
I think there's an issue with your Jest configuration, as you've seen by the folder structure we distribute to NPM, the package is exported as an ESM module with it's typings.

**Comment by JonatanSalas** [comment]
Closing the issue because no comments left from the latest one!

**Comment by serranomorante** [comment]
Same issue here. I couldn't find any solution for this.

**Comment by JonatanSalas** [comment]
Maybe including `node_modules` in `moduleDirectories` config for jest?

**Comment by serranomorante** [comment]
Even without *Create React App* and using only *jest* (instead of `react-scripts test`)... `moduleDirectories` doesn't work. I'm so lost on this one.
