### ISSUE TITLE
does not work when creating provider version 3.17.1

### ISSUE THREAD

**Issue by fgcamm** [BlackBoxVision/react-admin-extensions#5]
This is how the translation works in react-admin 3.17.1

`import polyglotI18nProvider from "ra-i18n-polyglot";
import spanishMessages from "@blackbox-vision/ra-language-spanish";

export const i18nProvider =  polyglotI18nProvider(() => spanishMessages, 'es', {
  allowMissing: true,
});
`

**Comment by aromeoes** [comment]
Same issue here

**Comment by jodaz** [comment]
On react-admin 3.18.1, only works when returning messages object. E.g:

```
export const i18nProvider = polyglotI18nProvider(() => spanishMessages);
```
