### ISSUE TITLE
Cannot find module & Unable to resolve path to module - '@blackbox-vision/ra-language-spanish/'

### ISSUE THREAD

**Issue by Arkellys** [BlackBoxVision/react-admin-extensions#7]
If I import the library as:

```js
import spanishMessages from "@blackbox-vision/ra-language-spanish/";
```

It works, but get the following ESLint errors:

```
Unable to resolve path to module "@blackbox-vision/ra-language-spanish/"
Missing file extension for "@blackbox-vision/ra-language-spanish/"
```

And my tests fail:
```js
Cannot find module '@blackbox-vision/ra-language-spanish/' from 'src/providers/translation/locales/es.js'
```

I can fix the ESLint errors if I import as `@blackbox-vision/ra-language-spanish/dist-src` or `/dist-web` but my tests still fail with:

```js
export default spanishMessages;
^^^^^^
SyntaxError: Unexpected token 'export'
```

I only managed to make everything work by updating the jest config in my `package.json`:

```json
"jest": {
   "transformIgnorePatterns": [
      "node_modules/(?!@blackbox-vision)"
   ]
}
```

I don't understand why I have to do this,  I am missing something?

---
Versions:

- `@blackbox-vision/ra-language-spanish` - 3.16.2
- `react-admin` - 3.19.1
- `yarn` - 1.22.10
- `node` - 14.18.1

**Comment by serranomorante** [comment]
I'm having the same issue. Using `transformIgnorePatterns` didn't work for me.
